const Map = require('../models/map');

const getUserMaps = async (req, res) => {
    try {
      const { email } = req.body;
  
      // Find maps generated by this user
      const userMaps = await Map.find({ userEmail: email });
  
      res.status(200).json(userMaps);
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };

module.exports = { getUserMaps};
