const Map = require('../models/map');

// Controller for saving the generated image
const saveGeneratedMap = async (req, res) => {
  try {
    const { imageUrl, imageName, userEmail } = req.body;
    
    // Create a new map document
    const newMap = new Map({
      imageUrl,
      imageName,
      userEmail,
    });

    // Save the map document in the database
    await newMap.save();

    // Respond with the saved map
    res.status(201).json(newMap);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
const getUserMaps = async (req, res) => {
    try {
      const { email } = req.params;
  
      // Find maps generated by this user
      const userMaps = await Map.find({ userEmail: email });
  
      res.status(200).json(userMaps);
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };

module.exports = { saveGeneratedMap,getUserMaps};
